# Generated by Django 4.1.1 on 2022-11-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Город"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Entrances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="Подъезд")),
                (
                    "slug",
                    models.SlugField(max_length=25, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Подъезд",
                "verbose_name_plural": "Подъезды",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Flats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="Квартира")),
                (
                    "slug",
                    models.SlugField(max_length=25, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Квартира",
                "verbose_name_plural": "Квартира",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Homes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=25, verbose_name="Дом"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=25, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Дом",
                "verbose_name_plural": "Дома",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Streets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Улица"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="promo.cities",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Улица",
                "verbose_name_plural": "Улицы",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camp", models.CharField(max_length=255, verbose_name="Кампания")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                ("photo", models.ImageField(upload_to="photo/%Y/%m/%d/")),
                (
                    "is_door_open",
                    models.CharField(
                        choices=[("yes", "Да"), ("no", "Нет")],
                        max_length=50,
                        verbose_name="Дверь открыли?",
                    ),
                ),
                (
                    "flat_owner",
                    models.CharField(max_length=255, verbose_name="Владелец квартиры"),
                ),
                (
                    "opinion",
                    models.CharField(
                        choices=[
                            ("positive", "позитивно"),
                            ("neutral", "нейтрально"),
                            ("negative", "негативно"),
                        ],
                        max_length=50,
                        verbose_name="Мнение",
                    ),
                ),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="promo.cities",
                        verbose_name="Город",
                    ),
                ),
                (
                    "entrance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="promo.entrances",
                        verbose_name="Подъезд номер",
                    ),
                ),
                (
                    "flat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="promo.flats",
                        verbose_name="Квартира",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="promo.homes",
                        verbose_name="Дом номер",
                    ),
                ),
                (
                    "street",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="promo.streets",
                        verbose_name="Улица",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промо кампания",
                "verbose_name_plural": "Промо кампании",
                "ordering": ["-time_create", "camp"],
            },
        ),
    ]
